version: 2

project_name: af

builds:
  - id: af
    main: ./cmd/af
    binary: af
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/kakkoyun/af/internal/version.Version={{.Version}}
      - -X github.com/kakkoyun/af/internal/version.Commit={{.Commit}}
      - -X github.com/kakkoyun/af/internal/version.Date={{.Date}}

archives:
  - id: af
    name_template: "af_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz

checksum:
  name_template: "af_{{.Version}}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

release:
  disable: true
