package config_test

import (
	"context"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kakkoyun/af/internal/config"
)

func TestUserConfigTemplate_DecodesToDefaults(t *testing.T) {
	template := config.UserConfigTemplate()

	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")
	writeFile(t, path, template)

	got, err := config.LoadWithOptions(context.Background(), config.LoadOptions{
		UserConfigPath: path,
	})
	if err != nil {
		t.Fatalf("LoadWithOptions() error = %v; template:\n%s", err, template)
	}

	want := config.Defaults()
	// The template is rendered through HOME expansion via Load; align that.
	home, err := os.UserHomeDir()
	if err != nil {
		t.Fatalf("UserHomeDir: %v", err)
	}
	want.General.WorktreeRoot = filepath.Join(home, "Workspace", ".worktrees")

	if got.SchemaVersion != want.SchemaVersion {
		t.Fatalf("SchemaVersion = %d, want %d", got.SchemaVersion, want.SchemaVersion)
	}
	if got.General.DefaultAgent != want.General.DefaultAgent {
		t.Fatalf("DefaultAgent = %q, want %q", got.General.DefaultAgent, want.General.DefaultAgent)
	}
	if got.General.WorktreeRoot != want.General.WorktreeRoot {
		t.Fatalf("WorktreeRoot = %q, want %q", got.General.WorktreeRoot, want.General.WorktreeRoot)
	}
	if got.General.MaxSessions != want.General.MaxSessions {
		t.Fatalf("MaxSessions = %d, want %d", got.General.MaxSessions, want.General.MaxSessions)
	}
	if strings.Join(got.Diff.Command.Argv, " ") != strings.Join(want.Diff.Command.Argv, " ") {
		t.Fatalf("Diff.Command.Argv = %v, want %v", got.Diff.Command.Argv, want.Diff.Command.Argv)
	}
	if strings.Join(got.PR.Command.Argv, " ") != strings.Join(want.PR.Command.Argv, " ") {
		t.Fatalf("PR.Command.Argv = %v, want %v", got.PR.Command.Argv, want.PR.Command.Argv)
	}
	if got.Obsidian.NotesFolder != want.Obsidian.NotesFolder {
		t.Fatalf("NotesFolder = %q, want %q", got.Obsidian.NotesFolder, want.Obsidian.NotesFolder)
	}
}

// TestUserConfigTemplate_UsesRealHomeDirNotPlaceholder guards issue #17:
// the [obsidian.vaults] example paths must be derived from the actual
// user's home directory at generation time, never the hardcoded
// "/Users/owner" placeholder that silently broke every new user's
// Obsidian integration.
func TestUserConfigTemplate_UsesRealHomeDirNotPlaceholder(t *testing.T) {
	home, err := os.UserHomeDir()
	if err != nil {
		t.Fatalf("UserHomeDir: %v", err)
	}

	template := config.UserConfigTemplate()

	if strings.Contains(template, "/Users/owner") {
		t.Fatalf("template still contains the /Users/owner placeholder:\n%s", template)
	}
	wantPersonal := filepath.Join(home, "Vaults", "personal")
	wantWork := filepath.Join(home, "Vaults", "work")
	if !strings.Contains(template, wantPersonal) {
		t.Fatalf("template missing real-home personal vault path %q; template:\n%s", wantPersonal, template)
	}
	if !strings.Contains(template, wantWork) {
		t.Fatalf("template missing real-home work vault path %q; template:\n%s", wantWork, template)
	}
	// notes_vault stays empty by default; the integration is opt-in.
	if !strings.Contains(template, `notes_vault    = ""`) {
		t.Fatalf("template must default notes_vault to empty; template:\n%s", template)
	}
}

func TestUserConfigTemplate_IsAnnotatedWithSectionComments(t *testing.T) {
	template := config.UserConfigTemplate()

	for _, marker := range []string{
		"# Generated by `af config init`",
		"[obsidian.vaults]",
		"# personal = ",
	} {
		if !strings.Contains(template, marker) {
			t.Fatalf("template missing marker %q; template:\n%s", marker, template)
		}
	}
}

func TestWriteUserConfig_CreatesParentDirsAndFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "nested", "subdir", "config.toml")

	err := config.WriteUserConfig(path)
	if err != nil {
		t.Fatalf("WriteUserConfig() error = %v", err)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat %s: %v", path, err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Fatalf("file mode = %v, want 0600", info.Mode().Perm())
	}

	body, err := os.ReadFile(path) //nolint:gosec // path is constructed under t.TempDir().
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if !strings.Contains(string(body), "schema_version = 1") {
		t.Fatalf("file body missing schema_version; got:\n%s", body)
	}
}

func TestWriteUserConfig_RefusesToOverwriteExistingFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")
	writeFile(t, path, "schema_version = 1\n")

	err := config.WriteUserConfig(path)
	if err == nil {
		t.Fatal("WriteUserConfig() error = nil, want overwrite-refusal")
	}
	if !errors.Is(err, fs.ErrExist) {
		t.Fatalf("WriteUserConfig() error = %v, want fs.ErrExist", err)
	}
}

func TestWriteUserConfig_RequiresAbsoluteOrCwdRelativePath(t *testing.T) {
	err := config.WriteUserConfig("")
	if err == nil {
		t.Fatal("WriteUserConfig(\"\") error = nil, want non-nil")
	}
}
