package config

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

const (
	userConfigTemplateBody = `# Generated by ` + "`af config init`" + `.
# See ADR-036 for the canonical schema.
#
# Three-layer merge: compiled defaults < this file < <repo>/.af/config.toml.

schema_version = 1

[general]
default_agent = "pi"            # one of: pi | claude | codex
multiplexer   = "tmux"          # only "tmux" in v1
max_sessions  = 10              # cap on concurrent workstreams
worktree_root = "~/Workspace/.worktrees"

[branch]
prefix              = ""        # empty = no prefix; e.g. "kakkoyun"
prefix_on_fork_only = true      # only apply when "upstream" remote exists

[editor]
terminal = "$EDITOR"            # falls back to nvim if $EDITOR unset
visual   = ""                   # empty = auto-detect: code > zed

[diff]
shell = false                   # argv-mode is safer; flip to true for shell strings
cmd   = ["git", "diff", "{base}...HEAD"]

[pr]
shell    = false
cmd      = ["gh", "pr", "create", "--base", "{base}", "--head", "{head}"]
template = ""                   # path to PR template (default: repo's .github/PULL_REQUEST_TEMPLATE.md)
ai_model = ""                   # default model override for ` + "`af pr --ai`" + ` (ADR-057); "" = agent default

[pr.flag_template]
body  = ["--body", "{body}"]
draft = ["--draft"]
title = ["--title", "{title}"]
web   = ["--web"]

[remote]
default_host = ""               # empty = remote requires explicit --remote arg
ssh_options  = ["-o", "ServerAliveInterval=60"]

[sandbox]
default_provider = ""           # empty | "slicer" | "sbx"

[sandbox.slicer]
group = ""                      # slicer host group; empty = auto

[sandbox.sbx]
image = ""                      # sbx default image override

[obsidian]
notes_vault    = ""             # vault key from [obsidian.vaults] below
notes_folder   = "00 - workstreams"
notes_template = ""             # optional path to a markdown template
notes_subfolder_mode = "repo"   # "repo" (default) nests notes per-repo; "flat" is the pre-issue-#34 layout

[obsidian.vaults]
# Map of vault-name -> absolute path on this machine. Multiple entries allowed.
# THIS SECTION IS GLOBAL ONLY: never appears in <repo>/.af/config.toml.
# personal = "{{personal_vault_example}}"
# work     = "{{work_vault_example}}"

[doctor]
extra_tools = []                # extra binaries to probe beyond the built-in defaults

[secret]
keyring_service = "af"          # service name passed to zalando/go-keyring (ADR-049)
redact_keys     = []             # extra slog attribute keys to redact

[status]
max_parallel = 8                # cap on concurrent gh pr view fetches (ADR-054)

[lifecycle]
retention_days = 90             # archive expiry (reserved; not enforced in v1)
auto_archive   = true           # move completed sessions to archive/ on ` + "`af done`" + `
`

	userConfigFilePerm = 0o600
	userConfigDirPerm  = 0o750
)

// ErrEmptyPath reports that an empty path was passed to WriteUserConfig.
var ErrEmptyPath = errors.New("config path is empty")

// UserConfigTemplate returns the annotated TOML template emitted by
// `af config init`. The body decodes back to Defaults() via Load.
//
// The example paths commented out under [obsidian.vaults] are derived
// from the current user's home directory (os.UserHomeDir) at call
// time, so a freshly generated config never ships another user's
// placeholder path (issue #17). notes_vault itself stays "" — the
// Obsidian integration remains opt-in until the operator uncomments
// and points a vault entry themselves.
func UserConfigTemplate() string {
	return renderUserConfigTemplate()
}

// exampleVaultPaths returns plausible personal/work vault paths rooted
// at the current user's home directory, falling back to "~" if the
// home directory cannot be resolved.
func exampleVaultPaths() (string, string) {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		home = "~"
	}
	return filepath.Join(home, "Vaults", "personal"), filepath.Join(home, "Vaults", "work")
}

// renderUserConfigTemplate substitutes the real-home vault placeholders
// into userConfigTemplateBody.
func renderUserConfigTemplate() string {
	personal, work := exampleVaultPaths()
	replacer := strings.NewReplacer(
		"{{personal_vault_example}}", personal,
		"{{work_vault_example}}", work,
	)
	return replacer.Replace(userConfigTemplateBody)
}

// WriteUserConfig writes the user-config template to path.
//
// Parent directories are created with 0750 permissions. The file is
// written with 0600 permissions. It refuses to overwrite an existing
// file by returning a wrapped fs.ErrExist.
func WriteUserConfig(path string) error {
	if path == "" {
		return fmt.Errorf("write user config: %w", ErrEmptyPath)
	}

	_, err := os.Stat(path)
	switch {
	case err == nil:
		return fmt.Errorf("write user config %s: %w", path, fs.ErrExist)
	case !errors.Is(err, fs.ErrNotExist):
		return fmt.Errorf("stat user config %s: %w", path, err)
	}

	err = os.MkdirAll(filepath.Dir(path), userConfigDirPerm)
	if err != nil {
		return fmt.Errorf("create parent dir for %s: %w", path, err)
	}

	err = os.WriteFile(path, []byte(renderUserConfigTemplate()), userConfigFilePerm)
	if err != nil {
		return fmt.Errorf("write user config %s: %w", path, err)
	}

	return nil
}

// ResolveUserConfigPath returns override if non-empty, otherwise the
// default user config path under $HOME/.config/af/config.toml.
func ResolveUserConfigPath(override string) (string, error) {
	return resolveUserConfigPath(override)
}
